# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f727c9c2da2db9c70406f4b4ab0b5e819e7bba63e95dc9dd55b67de46ed7727e6801ea406b84151d2d9b08bee56815beeddc0916b47a2327eb0020c60276c9c

test:
  secret_key_base: c24d588e187792cec73477184455a9ee69027119496efc6af9d3c0e4bad4d24ae4017e6698d1882d083f1495e4608e45318594e37366f7f8fc3df4d9325827c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
